import React from 'react';
import '../styles/home.css';
import TrainCard from '../components/trainCard.js';

const Home = () => {

  const trains = [
    {
      route: 'Batticaloa - Colombo Fort',
      trainNo: '6012',
      trainName:'Udaya Devi',
      type: 'Express',
      days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun, Poya, Holi',
      startTime: '6:10:00',
      endTime: '3:05:00',
      startStation: 'Batticaloa',
      endStation: 'Colombo Fort',
      duration: '8 h 55 m',
      lastUpdateStation: 'Konwewa',
      lastUpdateTime: '12:33 PM',
      stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
    },
  {
    route: 'Kandy - Colombo Fort',
    trainNo: '1041',
    trainName: 'Podi Menike',
    type: 'Express',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun',
    startTime: '5:55:00',
    endTime: '9:30:00',
    startStation: 'Kandy',
    endStation: 'Colombo Fort',
    duration: '3 h 35 m',
    lastUpdateStation: 'Peradeniya',
    lastUpdateTime: '6:20 AM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  },
  {
    route: 'Galle - Colombo Fort',
    trainNo: '8021',
    trainName: 'Ruhunu Kumari',
    type: 'Express',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun, Poya, Holi',
    startTime: '6:00:00',
    endTime: '8:50:00',
    startStation: 'Galle',
    endStation: 'Colombo Fort',
    duration: '2 h 50 m',
    lastUpdateStation: 'Aluthgama',
    lastUpdateTime: '7:10 AM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  },
  {
    route: 'Matara - Kandy',
    trainNo: '4075',
    trainName: 'Rajarata Rajina',
    type: 'Express',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun',
    startTime: '5:00:00',
    endTime: '11:30:00',
    startStation: 'Matara',
    endStation: 'Kandy',
    duration: '6 h 30 m',
    lastUpdateStation: 'Galle',
    lastUpdateTime: '5:45 AM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  },
  {
    route: 'Colombo Fort - Vavuniya',
    trainNo: '4031',
    trainName: 'Uttara Devi',
    type: 'Express',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun, Poya',
    startTime: '12:50:00',
    endTime: '7:25:00',
    startStation: 'Colombo Fort',
    endStation: 'Vavuniya',
    duration: '6 h 35 m',
    lastUpdateStation: 'Kurunegala',
    lastUpdateTime: '2:45 PM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  },
  {
    route: 'Badulla - Colombo Fort',
    trainNo: '1002',
    trainName: 'Night Mail',
    type: 'Mail',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun, Poya',
    startTime: '8:00:00',
    endTime: '5:10:00',
    startStation: 'Badulla',
    endStation: 'Colombo Fort',
    duration: '9 h 10 m',
    lastUpdateStation: 'Haputale',
    lastUpdateTime: '9:20 PM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  },
  {
    route: 'Colombo Fort - Galle',
    trainNo: '8058',
    trainName: 'Sagarika',
    type: 'Express',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun',
    startTime: '4:30:00',
    endTime: '6:45:00',
    startStation: 'Colombo Fort',
    endStation: 'Galle',
    duration: '2 h 15 m',
    lastUpdateStation: 'Panadura',
    lastUpdateTime: '5:05 PM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  },
  {
    route: 'Colombo Fort - Trincomalee',
    trainNo: '6013',
    trainName: 'Koneswaram Express',
    type: 'Express',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun, Poya',
    startTime: '6:30:00',
    endTime: '2:55:00',
    startStation: 'Colombo Fort',
    endStation: 'Trincomalee',
    duration: '8 h 25 m',
    lastUpdateStation: 'Galoya Junction',
    lastUpdateTime: '11:50 AM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  },
  {
    route: 'Colombo Fort - Jaffna',
    trainNo: '4019',
    trainName: 'Yal Devi',
    type: 'Express',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun, Poya',
    startTime: '8:00:00',
    endTime: '4:25:00',
    startStation: 'Colombo Fort',
    endStation: 'Jaffna',
    duration: '8 h 25 m',
    lastUpdateStation: 'Maho',
    lastUpdateTime: '10:15 AM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  },
  {
    route: 'Colombo Fort - Puttalam',
    trainNo: '5065',
    trainName: 'Puttalam Express',
    type: 'Express',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun',
    startTime: '4:00:00',
    endTime: '7:45:00',
    startStation: 'Colombo Fort',
    endStation: 'Puttalam',
    duration: '3 h 45 m',
    lastUpdateStation: 'Negombo',
    lastUpdateTime: '5:20 PM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  },
  {
    route: 'Kandy - Ella',
    trainNo: '1015',
    trainName: 'Udarata Menike',
    type: 'Express',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun, Poya',
    startTime: '8:30:00',
    endTime: '3:55:00',
    startStation: 'Kandy',
    endStation: 'Ella',
    duration: '7 h 25 m',
    lastUpdateStation: 'Hatton',
    lastUpdateTime: '11:15 AM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  },
  {
    route: 'Colombo Fort - Polonnaruwa',
    trainNo: '4096',
    trainName: 'Pulathisi Express',
    type: 'Express',
    days: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun, Poya',
    startTime: '3:00:00',
    endTime: '9:10:00',
    startStation: 'Colombo Fort',
    endStation: 'Polonnaruwa',
    duration: '6 h 10 m',
    lastUpdateStation: 'Kurunegala',
    lastUpdateTime: '4:20 PM',
    stoppingStations: ['Station 1', 'Station 2', 'Station 3', 'Station 4'],
  }  
  ];

  return (
    <div className="home-page">
      <div className="container train-card-container">
        {trains.map((train, index) => (
          <TrainCard key={index} train={train} />
        ))}
      </div>
    </div>
  );
};

export default Home;
